rust-lang/pkg-config-rs

src/lib.rs, tests/disabled.rs
This is useful in build scripts for extracting data from .pc files when the situation is more complex than just extracting some linker flags.
My particular case is for working out the path to the python interpreter so I can interrogate it for build flags.
=> add Config::get_variable

Cargo.toml, src/lib.rs, tests/test.rs
Allow users to distinguish between pkg-config being disabled by an environment variable, missing and genuinely failing.
=> Make the error more strongly typed

src/lib.rs, tests/test.rs
This will mimic PKG_CONF_PKG_CONFIG m4 macro.
Useful e.g. when using alternatives like pkgconf or when prefixing like x86_64-pc-linux-gnu-pkg-config (in a distro with native cross-compilation).
=> Use PKG_CONFIG environment variable

src/lib.rs
It can resolve cyndis/qmlrs#39.
=> Fix the bug that duplicating 'cargo:' prefix in OS X framework output, and other minor bugs.

README.md, src/lib.rs
Suggest using the metadeps crate to declare pkg-config dependencies in
`Cargo.toml`.
Also, update the documentation and examples to recommend always using a
minimum version requirement for libraries.
=> Mention metadeps

src/lib.rs, tests/framework.pc, tests/test.rs
Should solve issue #47 
`-Wl,A,B,C` is passed as `A B C` to the linker and some `.pc` files specify frameworks to link to this way: `-Wl,-framework,Framework` or  `-Wl,-framework -Wl,Framework` (instead of `-framework Framework` as is currently supported by this crate).
This PR just adds support for specifying frameworks in those other ways as well.
=> Added support for parsing `-Wl,` style framework flags

src/lib.rs
I need the defines to forward to the `extern crate cc` builder to build a C helper file.
=> Parse defines in `pkg-config` output.

.gitignore, README.md, src/lib.rs
This introduce target-scoped variables for PKG_CONFIG_PATH, PKG_CONFIG_LIBDIR and PKG_CONFIG_SYSROOT_DIR, mimicking cc-rs for the target-scoping conventions.
=> Introduce target-scoped variables

src/lib.rs, tests/escape.pc, tests/test.rs
* When processing output of --cflags / --libs, interpret backslash as an
escape character preserving literal meaning of next byte and split
output into words using unescaped whitespace characters.
* Return `Vec<u8>` from run function instead of `String`, to support cases
where output becomes a valid UTF-8 string only after processing escapes.
Tested on Linux with:
* pkg-config: 0.29
* OpenBSD pkg-config: 0.27.1
* pkgconf: 0.28
Fixes issue #60.
=> Respect pkg-config escaping rules used with --cflags and --libs.

src/lib.rs
This was removed in b5c7936aa8b78eb0faf28176fec0ce21930679fb, but breaks compatibility with Rust <1.23.
See #64
=> Re-add AsciiExt import

.travis.yml, README.md
Since we're using the `?` operator, 1.13 is the lowest Rust version that
still builds.
This commit specifies 1.13 as the lowest supported Rust version and adds
a CI testing step. Changes in the minimal required version should be
considered breaking changes.
Fixes #64
=> Specify 1.13 as lowest required Rust version

src/lib.rs
=> Add support for MSVC

src/lib.rs
rustc already does that itself. As such, the only difference between
MSVC and other platforms is to skip a couple of libraries that are often
wrongly added by pkg-config.
----
This didn't cause problems for me in the past because of https://github.com/gtk-rs/sys/blob/cdc7f613c2ed1e4f021a2c83d6f51469edc03eb1/glib-sys/build.rs#L66 and similar code.
Also e.g. https://github.com/alexcrichton/libz-sys/commit/d52034109e6eeb7e1fb72cadcc364f7d961b5882 should IMHO be reverted (and there the workaround for macOS is going to cause problems too)
=> Don't append .lib suffix on MSVC builds

README.md, src/lib.rs
The use of std::ops::RangeBounds makes it impossible to support < 1.28
This commit removes the monkeypatched Debug impl for Error in favor of
the built-in one since 1.7
=> Changes minimum documented rust version to 1.28

Cargo.toml, README.md
=> Fix Travis CI badge url

README.md
The text refers to Serde instead of pkg-config-rs.
Signed-off-by: Daniel Verkamp <dverkamp@chromium.org>
=> Fix contribution license project name

src/lib.rs, tests/test.rs
Implements #41
- if pkg-config appears to be customized for cross-compilation (sets `PKG_CONFIG_SYSROOT_DIR` or a wrapper script), then allow cross-compilation by default
- `PKG_CONFIG_ALLOW_CROSS=0` disables the heuristic and always forbids
- uses `targetted_env_var` helper method, so it will also recognize per-target settings and correctly re-check if the env vars change.
=> Allow cross-compilation if pkg-config is customized

.travis.yml, CHANGELOG.md, Cargo.toml
Release preparations like updating changelog, version number, etc.
=> 0.3.15 release

src/lib.rs, tests/test.rs
ran with rustfmt 1.3.0-stable (d334502 2019-06-09)
I wanted to do this separately from #88 and will rebase that when the time comes.
=> run cargo fmt

src/lib.rs
Closes #92.
freedesktop.org pkg-config and pkgconf both respect this environment variable to avoid having CFLAGS simplified as described in #92, so make use of it.
=> add support for PKG_CONFIG_ALLOW_SYSTEM_CFLAGS

src/lib.rs
Only return the first line in `parse_modversion`. I added a test that demonstrates the issue and confirms that it's fixed.
=> Fixes #95 - multiple version numbers

src/lib.rs
`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon. `Error::cause` has already been deprecated since 1.33.0.
This PR:
- Removes the implementations of `description` and `cause` 
Related PR: https://github.com/rust-lang/rust/pull/66919
=> Remove deprecated Error::description and Error::cause

src/lib.rs
`pkg-config` depends on a variety of environment variables to inform
itself on where to look information about the libraries requested. By
default the crate has chosen to not inform `cargo` about these
variables, leading to problems that usually arise from `cargo` having
incomplete understanding of the dependency information.
In particular, changing `PKG_CONFIG_PATH` variable would more likely
than not fail to rebuild various dependencies that discover their
linkage information via `pkg-config`. This behaviour is confusing.
Developers will generally not fiddle with these environment variables
however, leading to most of the crate ecosystem not setting
`env_metadata` to `true`.
This commit adjusts the default for `env_metadata` to `true` to achieve
the "correct" behaviour in the typical …
=> Default the `env_metadata` build parameter to `true`

README.md, src/lib.rs
I've noticed it already auto-detects `PKG_CONFIG_SYSROOT_DIR`, so it's enough to document this.
Fixes #109
=> Improve docs for cross-compilation

src/lib.rs
Use the PKG_CONFIG_SYSROOT_DIR (preferred) or SYSROOT (fallback)
environment variables to override the default path used to determine
whether a library is a system library or not (/usr).
This enables cross-compilation scenarios where the system root is not a
subdirectory of /usr. Specifically, when building Rust packages in the
Chomium OS SDK, each board's sysroot is located in /build/$BOARD rather
than a subdirectory of /usr. Additionally, cros_sdk only specifies
SYSROOT (PKG_CONFIG_SYSROOT_DIR is set by the pkg-config-$BOARD cross
compilation helpers, but that isn't available in pkg-config-rs).
This has only been tested on Linux, as I don't have a macOS machine
handy, but I believe the macOS path should work as before (it does not
consider the new sysroot variables).
Signed-off-by: …
=> Allow overriding system root via environment

src/lib.rs
[#86](https://github.com/rust-lang/pkg-config-rs/pull/86#discussion_r767045433)
=> Fix semver break of target_supported

src/lib.rs, tests/rpath.pc, tests/test.rs
I'm not quite sure if this project wants to support it, but it would be a nice to have in my opinion.
=> Adding rpath support

src/lib.rs
Typically pkgconfig files specify cflags for linking with -L and -l,
however, pkgconfig files can also specify paths to library files. For
example, building Qt5 statically on macOS generates the following
pkgconfig file. Notice the absolute path to libqtpcre.a in Libs.private:
```
prefix=/Users/be/qt5-installed
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include
host_bins=${prefix}/bin
qt_config=debug_and_release release debug build_all c++11 c++14 c++17 c++1z concurrent dbus no-pkg-config reduce_exports release_tools static stl
Name: Qt5 Core
Description: Qt Core module
Version: 5.15.5
Libs: -L${libdir} -lQt5Core
Libs.private: -framework DiskArbitration -framework IOKit -lm -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices …
```
=> handle file paths to libraries

src/lib.rs
=> Pass -l:libfoo.a to linker directly.

src/lib.rs
No functional change.
sucessfully -> successfully
targetted -> targeted
manualy -> manually
=> Fix spelling.

src/lib.rs
I've noticed that people trying to build a crate which links against a missing library [can sometimes be confused](https://pijul.zulipchat.com/#narrow/stream/270693-general/topic/cargo.20install.20problem.20-.20macOS) by this library's error output. This PR introduces a re-worked error message for that case that focuses on communicating:
- What's gone wrong?
- How can I diagnose the cause?
- What can I do to fix this?
Before (trimmed `build.rs` output for [libsodium-sys-stable](https://github.com/jedisct1/libsodium-sys-stable)):
```
--- stderr
thread 'main' panicked at build.rs:128:13:
Error: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "libsodium"` did not exit successfully: exit status: 1
error: could not find system library …
```
=> Improve error message when a library is not found

src/lib.rs
Hi!
This PR is intended to address some issues found when attempting to link to static libraries under Windows.
- `-Wl,--undefined` flags were silently skipped.
- `is_static_available` does not consider Windows SDK or CRT bindings.
- Allows using the `.a` and `.dll.a` convention for MSVC as well, thus letting Meson-built libraries be used.
CC @nirbheek
=> Fix Windows static library detection and usage

src/lib.rs
Document pkg-config cross compilation environment
variables in library documentation.
Fixes #156
=> Update docs for cross compilation.

src/lib.rs
=> style: prefer immutable

.github/workflows/ci.yml, Cargo.lock.msrv, Cargo.toml, README.md, src/lib.rs, tests/test.rs
This crate is one of the last ones on the edition 2015.
=> Update to edition 2018

src/lib.rs
`print_metadata` adds `"cargo:"`, so this prints `cargo:cargo:rustc-link-arg=`.
=> Fix double cargo: prefix

src/lib.rs
Otherwise, we are still not copy-paste friendly.
Ref: #174
Fixes: a0640aadcb ("Wrap std::process::Command to track arguments and environment variables")
=> Quote WrappedCommand arguments with spaces in them

src/lib.rs
On homebrew side, we have migrated to use `pkgconf` for all core formulae and now have everyone use `pkgconf` rather than `pkg-config`.
- https://github.com/Homebrew/brew/pull/18843
=> Use `pkgconf` instead of `pkg-config` for brew builds
